automatic update: 18-02-2021 at 14:03:16

diff --git a/launchd/install_launchd_service b/launchd/install_launchd_service
--- a/launchd/install_launchd_service
+++ b/launchd/install_launchd_service
@@ -8,10 +8,9 @@ cd $DIR
 FILE=$(ls *.plist| head -1) # Returns first .plist file in folder
 SERVICE=${FILE%.plist} # Strips .plist
 NAME=${SERVICE##*.} # Gets part of service name after last dot
-NAME_UPPER=${NAME^}
 
 # Unload if service already loaded
-if [[ $(launchctl list | grep $SERVICE > /dev/null) ]]; then
+if [[ $(launchctl list | grep $SERVICE) > /dev/null ]]; then
     echo 'Service already loaded – unloading and reloading'
     launchctl unload ~/Library/LaunchAgents/$FILE
 fi
@@ -21,11 +20,11 @@ cp $DIR/$FILE ~/Library/LaunchAgents/
 launchctl load ~/Library/LaunchAgents/$FILE
 
 # Check that service is running
-if [[ $(launchctl list | grep $SERVICE > /dev/null) ]]; then
-    echo 'Launchd service '$NAME_UPPER' installed successfully'
+if [[ $(launchctl list | grep $SERVICE) > /dev/null ]]; then
+    echo 'Launchd service '$NAME' installed successfully'
 else
-    echo 'Failed to install '$NAME_UPPER' launchd service'
-    exit 1
+    echo 'Failed to install '$NAME' launchd service'
+    (exit 1)
 fi
 
 # Keep terminal open
