automatic update: 18-02-2021 at 13:49:43

diff --git a/launchd/install_launchd_service b/launchd/install_launchd_service
--- a/launchd/install_launchd_service
+++ b/launchd/install_launchd_service
@@ -7,20 +7,26 @@ cd $DIR
 # Find service plist
 FILE=$(ls *.plist| head -1) # Returns first .plist file in folder
 SERVICE=${FILE%.plist} # Strips .plist
-NAME=$(${SERVICE##*.} | echo $1) # Gets part of service name after last dot
+NAME=${SERVICE##*.} # Gets part of service name after last dot
+NAME_UPPER=${NAME^}
 
 # Unload if service already loaded
-launchctl list | grep $SERVICE > /dev/null \
-&& launchctl unload ~/Library/LaunchAgents/$FILE
+if [[ $(launchctl list | grep $SERVICE > /dev/null) ]]; then
+    echo 'Service already loaded – unloading and reloading'
+    launchctl unload ~/Library/LaunchAgents/$FILE
+fi
 
 # Copy plist and load launchd service
 cp $DIR/$FILE ~/Library/LaunchAgents/
 launchctl load ~/Library/LaunchAgents/$FILE
 
 # Check that service is running
-launchctl list | grep $SERVICE > /dev/null \
-&& echo 'Launchd service '$NAME' installed successfully' \
-|| (echo 'Failed to install '${NAME^}' launchd service'; exit 1)
+if [[ $(launchctl list | grep $SERVICE > /dev/null) ]]; then
+    echo 'Launchd service '$NAME_UPPER' installed successfully'
+else
+    echo 'Failed to install '$NAME_UPPER' launchd service'
+    exit 1
+fi
 
 # Keep terminal open
 echo ''
